### ISSUE TITLE
Add option to encrypt/decrypt state files

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#1]
If a user does not want to store the layout files in plaintext, then there should be an option to encrypt and decrypt the stored state

**Comment by joncrangle** [comment]
[Age encryption](https://github.com/FiloSottile/age) could be a good option for this. The downside is that it introduces a dependency, but it would allow encryption/decryption of json state files since `age` can be run as a child process and its results piped to stdout. The json file could then be encrypted/decrypted on demand when necessary, but would stay encrypted at rest as `default.json.age`.

In the plugin config, the user could supply something like:
```lua
resurrect.encrypt = {
      identity = "path/to/key.txt",
      recipient = "longpublickey",
}
```

This approach would also avoid plain text private keys being part of wezterm configs.

I use [chezmoi](https://www.chezmoi.io/) to manage my dotfiles, and it incorporates age encryption pretty seamlessly using this approach.

**Comment by MLFlexer** [comment]
I have not used age myself, but it looks cool.

It would however be a nice user experience if it was possible to opt into the encryption and if a user would be able to an encryption method of their liking.

I think a good middleground is to have a function call which takes the lines like so:
```lua
---@param file_path string
---@param state table
---@param encryption_func fun(lines: string[]): string[]
local function write_state(file_path, state, encryption_func)
	local file = assert(io.open(file_path, "w"))
	local lines = wezterm.json_encode(json_table)
	if encryption_func then
             lines = encryption_func(lines)
	end
	file:write(lines)
	file:close()
end
```
 Then the plugin can provide a default function, which uses age such that the dependency is not strictly nessisary. Then if the user wants to use another encryption, then we provide a way to use some other means of encryption.

What do you think about this approach?

**Comment by MLFlexer** [comment]
Thinking about it more, I think it would be a good idea to have the encryption process write the files, as that is supported by most external encryption programs, like age with the `-o` flag.

**Comment by joncrangle** [comment]
This looks fantastic. I'll give it a test when I have some time. [Rage encryption](https://github.com/str4d/rage) is a Rust implementation of the age protocol and is a drop-in replacement, so we could support both implementation with the same encryption/decryption functions. This implementation would also allow someone to provide their own functions if they prefer another encryption method (e.g GPG or others) which is nice. 

I saw in the wezterm issues that encryption of state files was a major reason for not including state saving within wezterm core, so this plugin and feature could fill in a major gap that is being requested by the community.

**Comment by MLFlexer** [comment]
I think that if other encryption implementations should be supported by the plugin, then they should be lazily loaded or only included as a documentation, as some users like to keep their plugins very minimal.

Either way I would like another document which describes how to setup the encryption for users and maybe a sub module which can optionally be required by the user (making it not loaded by default) and which contains easy encryption setups for other providers like GPG, openssl... and also setups for different operating systems like windows.
