### ISSUE TITLE
Windows: path elements with spaces need to be wrapped in quotes

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#22]
Ok - I've managed to get it working on Windows in a bit of a convoluted way with branch `19-unable-to-require-plugin`. I'll try on Mac and Arch later when I have some more time. 

I had `resurrect.init_directories()` commented out throughout the process.

1) `git clone https://github.com/MLFlexer/resurrect.wezterm.git` within `C:\Users\{USERNAME}\AppData\Roaming\wezterm\plugins\`
2) Checkout branch `19-unable-to-require-plugin`
3) I removed the "sZs" from the end of each entry in `init.lua`
4) Restarted wezterm. This resulted in a second resurrect directory being created in the plugin folder, so the directory contained  `httpssCssZssZsgithubsDscomsZsMLFlexersZsresurrectsDsweztermsZs/` and `httpssCssZssZsgithubsDscomsZsMLFlexersZsresurrectsDswezterm`. I made sure both resurrect plugin folders were on branch `19-unable-to-require-plugin` and restarted wezterm again.

If I remove either of these resurrect folders, the wezterm config crashes. But the plugin loads and works. I can save sessions.

A bug I've found with windows is that it will not "resurrect" properly because path elements with spaces need to be wrapped in quotes.

```bash
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.4.4.0_x64__8wekyb3d8bbwe\pwsh.exe
C:\Program: The term 'C:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

_Originally posted by @joncrangle in https://github.com/MLFlexer/resurrect.wezterm/issues/19#issuecomment-2259059385_

**Comment by joncrangle** [comment]
I'll take a look at this tomorrow on a Windows pc. I'll need to check the `state.json` file to see how the `pane_tree.process` key is formatted.

**Comment by MLFlexer** [comment]
> I think this can be resolved with a couple edits to `pane_tree.lua`:
> 
> ```lua
> 	elseif process == "pwsh.exe" then
> 		return process
> 	elseif process == "cmd.exe" then
> 		return process
> ```

I have added this in the PR

> On Windows, also need to remove the beginning forward slash from root.cwd in `pane_tree.lua`. This approach will remove it if it's followed by a letter and colon (e.g C:):
> 
> ```lua
> 	root.cwd = root.pane:get_current_working_dir().file_path
> 	root.cwd = root.cwd:gsub("^/([a-zA-Z]):", "%1:")
> ```

I have run the following:
```
wezterm.mux.get_pane(0):get_foreground_process_name()
"C:\\Windows\\System32\\cmd.exe"

wezterm.mux.get_pane(0):get_current_working_dir()
file:///C:/Users/Admin/
```

As you can see from the outputs, it does not seem to be a problem a problem with the CWD or the processes? Do you agree with this? @joncrangle
