### ISSUE TITLE
feat: toast notification on_save, on_resurrect, on_periodic_save, on_error

### ISSUE THREAD

**Issue by joncrangle** [MLFlexer/resurrect.wezterm#25]
Looking for your thoughts on a feature to initiate a toast notification following successful/unsuccessful plugin events. We could let the user override defaults according to their preference.

Wezterm provides a [window:toast_notification()](https://wezfurlong.org/wezterm/config/lua/window/toast_notification.html?h=toast) that we can use to provide some optional feedback:
```lua
window:toast_notification('Workspace state saved', nil, 4000)
```

Defaults could look something like:
```lua
---@class NotificationSettings
---@field on_save boolean
---@field on_resurrect boolean
---@field on_periodic_save boolean
---@field on_error boolean

---@type NotificationSettings
local default_notifications = {
	on_save = true,
	on_resurrect = false,
	on_periodic_save = false,
	on_error = true,
}

--- Changes the default notification settings
---@param settings NotificationSettings A table containing optional fields `on_save`, `on_resurrect`, `on_periodic_save` and `on_error`
function pub.notification(settings)
	for key, value in pairs(settings) do
		if default_notifications[key] ~= nil then
			default_notifications[key] = value
		end
	end
end
```

Then, depending on the value of default_notifications we could run a `window:toast_notification` function.

**Comment by joncrangle** [comment]
I'll play around with this feature a bit and make sure to set the defaults to only show a toast `on_error`. Personally, I would only use toasts `on_save` and `on_error`. I don't think an `on_resurrect` option is particularly useful since it is obvious when this succeeds. An `on_periodic_save` would be intrusive, but I could provide this option and disable it by default.

To send a toast, the user would need to call functions passing in a `window` object, so if no `window` object is passed in there wouldn't be any toasts. I'll make sure everything still operates without this opt to make sure the current API still works as-is.

**Comment by MLFlexer** [comment]
What if there was an event emitted when saving, resurrecting and for the periodic save via. [wezterm.emit](https://wezfurlong.org/wezterm/config/lua/wezterm/emit.html), then there could be a default [wezterm.on](https://wezfurlong.org/wezterm/config/lua/wezterm/on.html) callback which could show the toast. This could of course be disabled/enabled at will for the user.
This would also make it possible for users to have other callback functions when these events are emitted 

And then keep the toasts for `on_error` without a wezterm.emit?

**Comment by joncrangle** [comment]
Now that you bring up wezterm.emit, I think this is a better option than including toasts within the plugin. 

We could leave it entirely up to the user to setup wezterm.on events in their config if they would like toasts. 

We could emit events and errors and provide sample code in the docs about how to create toasts from these events, but the enjoyed events could be used for other purposes (for instance someone might want to initiate a syncthing process on save, or their own encryption mechanism outside of the plugin).

**Comment by MLFlexer** [comment]
I will make a new issue for implementing `wezterm.on` in the various functions.

I do like the idea of having some toast notification when an error occurs, like if there is an error when writing the file or if the user is trying to use encryption but havn't done the setup with their keys ect. Will also open a new issue for this
