### ISSUE TITLE
handle UNIX and TLS domains

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#40]
With #39 it is possible to restore certain domains, but UNIX and TLS domains are currently not supported. This is something which I don't have much experience with, as I don't use these domains on a daily. 
If you are a user of these domains, then please file issues or even better PRs, such that I can see there is a need for this as I currently wont prioritize this unless others would like it implemented.

**Comment by MLFlexer** [comment]
I have tried to setup a TLS domain, but it seems like i am only able to connect to it via. `wezterm connect <tls_server_name>` i.e. I am not able to connect to it within the same window as other non-tls-panes. Even when running wezterm connect --new-tab <tls_server_name>` it always spawns a new window and connects to it.

**Comment by joncrangle** [comment]
I can confirm that https://github.com/MLFlexer/resurrect.wezterm/pull/45 enables saving and restoring Unix domain sessions.

Steps I took:

1) Create a docker container with Wezterm installed:
```Dockerfile
FROM debian:latest

RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    sudo

RUN curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg \
    && echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list \
    && sudo apt-get update \
    && sudo apt-get install -y wezterm-nightly

CMD ["bash"]
```
2) Start the container with a long running process:
```bash
docker run -d --name wezterm-container wezterm-debian tail -f /dev/null
```
3) Add the container as a unix domain in Wezterm config:
```lua
config.unix_domains = {
  {
    name = "WEZDOCKER",
    proxy_command = { "docker", "exec", "-i", "[container_id]", "wezterm", "cli", "proxy" }
  }
}
```

**Comment by MLFlexer** [comment]
Awesome! Thanks for providing the steps to test it, makes it a lot easier for myself to test in the future! 😄
