### ISSUE TITLE
Named domains aren't restored

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#42]
If you have a named domain, say via the following config:

```lua
config.ssh_domains = {
		{
			name = "rpi5",
			remote_address = "192.168.0.42",
		},
	}
```

Then the domain wont be saved, as it is currently unsupported as it reaches the [else branch in pane_tree.lua](https://github.com/MLFlexer/resurrect.wezterm/blob/599958ea2df76bd4e581411420964f83d67332b3/plugin/resurrect/pane_tree.lua#L135)

**Comment by joncrangle** [comment]
I'll experiment a bit, but I don't think this bug will be terribly difficult to fix. 

We could check if domain ~= "local" first, and if so, save the domain key.

Alternatively, we can make the domain key non-optional and always save it.

**Comment by joncrangle** [comment]
I can confirm that https://github.com/MLFlexer/resurrect.wezterm/pull/45 saves and restores named ssh domains
