### ISSUE TITLE
gpg encryption not working (also error messages are not logged)

### ISSUE THREAD

**Issue by michaelbrusegard** [MLFlexer/resurrect.wezterm#46]
Hey, I just came across this project and as I was setting it up I was unable to get encryption working. I saw that the changes added were quite recent so I thought I could create an issue just in case. I have read both the code and the documentation (and I am not getting any error messages). It works without encryption enabled. I am using gpg in this case.

```lua
	resurrect.set_encryption({
		enable = true,
		method = "opt/homebrew/bin/gpg", -- Also tried with just 'gpg'
		public_key = [[
-----BEGIN PGP PUBLIC KEY BLOCK-----
mDMEZsKHLxYJKwYBBAHaRw8BAQdAYY8xYh6O8GEUO8wiAqKEqpReSGUoyriXO51m
I didnt bother adding the whole public key but you get the point
=207v
-----END PGP PUBLIC KEY BLOCK-----
    ]],
	})
```

**Comment by michaelbrusegard** [comment]
Forgot to mention, I also tested deleting al the plugin files after enabling encryption, but it did not help either

**Comment by MLFlexer** [comment]
Hey, Thanks for creating the issue! 
I don't have a Mac, but maybe we can try and figure out what is going on anyways.

The command that is being run is this:
```lua
cmd = string.format("%s --batch --yes --encrypt --recipient %s --output %s", pub.encryption.method, pub.encryption.public_key, file_path:gsub(" ", "\\ "))
```
i.e. the following: 
`gpg --batch --yes --encrypt --recipient <recipient_email_or_keyid> --output <output_file>`

You can try and change the `public_key` to be the `key_id` or email associated with the key.
You can list the keys with `gpg --list-keys`
This should produce an output like so:
```
$ gpg --list-keys

pub   rsa3072 2021-08-19 [SC] [expires: 2023-08-19]
      6D5A7D00E1A9DB75 (This is your key ID)
uid           [ultimate] Alice Example <alice@example.com> (this is your email)
sub   rsa3072 2021-08-19 [E] [expires: 2023-08-19]
```

This should probably be stated clearly in the README to avoid confusion

**Comment by MLFlexer** [comment]
Also did you check the debug overlay for missing errors, or where did you expect them to be? There should be errors, so if they are not in the debug overlay, then that is a bug.

**Comment by michaelbrusegard** [comment]
Thanks so much for the good answer, I am a little new to lua, wezterm and nvim in general so I do not know about the debug overlay. It worked when I used full path for gpg in the method (like with all utilities in wezterm I have noticed) and using the key id. I guss the Key id is public information so I dont need to be scared to push it to my dotfiles repo?

Unrelated: Thanks for the amazing plugins. One thing about workspaces I find a little annoying is that they manage all windows (since I am using a tiling window manager) so each workspaces can pop up multiple windows instead of being tied one. Is this solveable? I dont think so, since it may be a limitation in wezterm itself. And when I load a workspace using ressurect it opens the loaded setup in a new window instead of overtaking or closing the original one where i ressurected it from, is this the expected behaviour?

**Comment by MLFlexer** [comment]
> Thanks so much for the good answer, I am a little new to lua, wezterm and nvim in general so I do not know about the debug overlay. 

The debug overlay is very nice for testing or finding errors in wezterm, plugins or your config. The default keybinding is `CTRL+SHIFT+l`.

> It worked when I used full path for gpg in the method (like with all utilities in wezterm I have noticed) and using the key id. 

You probably need the full path because of [this](https://wezfurlong.org/wezterm/faq.html#im-on-macos-and-wezterm-cannot-find-things-in-my-path)
> I guss the Key id is public information so I dont need to be scared to push it to my dotfiles repo?

From my knowlegde, you should be able to share your key id with anyone, i.e. push it to your dotfiles.

> Unrelated: Thanks for the amazing plugins. 

Thanks for your nice comment! 😄 

> One thing about workspaces I find a little annoying is that they manage all windows (since I am using a tiling window manager) so each workspaces can pop up multiple windows instead of being tied one. Is this solveable? I dont think so, since it may be a limitation in wezterm itself.

From my understanding of wezterm (which might be wrong) a `workspace` is a collection of windows with tabs, panes ect. So each `workspace` will manage its own windows, which cannot be shared. I dont think you can have more than one workspace active at a time, so it might not solvable. However if your workspace only contains one window, then when you switch to that workspace it should only open that one window.

One suggestion is that you keep your workspaces to one window and manage that only.
Another would be to drop workspaces and use this plugin to load/save window states (i.e. all the tabs and panes for each window, instead of saving/loading workspaces which also contain windows). 

I dont personally use a tiling window manager and I usually only have one wezterm window open at a time so my usecase might differ a lot from yours. But I can try and help you configure a workflow which works for you if you can try and explain what you are looking for. As this workflow might also be useful for other users aswell 😄 

> And when I load a workspace using ressurect it opens the loaded setup in a new window instead of overtaking or closing the original one where i ressurected it from, is this the expected behaviour?

If you are using the fuzzy finder keybinding from the [setup-example](https://github.com/MLFlexer/resurrect.wezterm?tab=readme-ov-file#setup-example) then it will create new windows when choosing an element as to not close important panes from the "old" window. This is expected for the setup-example, but can be changed as it is just an example of a usecase.

**Comment by joncrangle** [comment]
> It worked when I used full path for gpg in the method (like with all utilities in wezterm I have noticed) and using the key id.

I had the same problem with Homebrew-installed apps on MacOS. On Mac, if you launch Wezterm by clicking WezTerm.app from your Applications folder, it will only have access to a default PATH that includes `usr/bin` and `usr/sbin`. Homebrew installs apps in a different location, so their binaries aren't found. As @MLFlexer pointed out, this is a MacOS issue: [Wezterm | F.A.Q.](https://wezfurlong.org/wezterm/faq.html#im-on-macos-and-wezterm-cannot-find-things-in-my-path)

The solution is to either 1) setup your Wezterm config like in the Wezterm FAQ so it has full access to your PATH, 2) launch Wezterm from another terminal (or even launch `wezterm` from the WezTerm.app instance) and it will have access to your declared PATH variables or, 3) as you mentioned, provide the full path to the gpg binary within the `method`.

**Comment by michaelbrusegard** [comment]
Thank you for the great help! Regarding workspaces and windows, I find I most often use a single window. Sometimes I do have secondary windows on other desktops, but I can live with them being removed when I switch workspace.

I was thinking (if I have time of course) to take out the statusline from my config and try to create a wezterm plugin of it that is similar to lualine for neovim, but I have never made a plugin before. Do you think that would be a nice addition?

<img width="1660" alt="Screenshot 2024-08-19 at 19 24 07" src="https://github.com/user-attachments/assets/642958a2-5db5-4c1c-9008-1ff6097e595c">

I am closing this issue since its resolved :)

**Comment by MLFlexer** [comment]
> Thank you for the great help! Regarding workspaces and windows, I find I most often use a single window. Sometimes I do have secondary windows on other desktops, but I can live with them being removed when I switch workspace.
> 
> I was thinking (if I have time of course) to take out the statusline from my config and try to create a wezterm plugin of it that is similar to lualine for neovim, but I have never made a plugin before. Do you think that would be a nice addition?
> <img alt="Screenshot 2024-08-19 at 19 24 07" width="1660" src="https://private-user-images.githubusercontent.com/56915010/359190038-642958a2-5db5-4c1c-9008-1ff6097e595c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODk4NjcsIm5iZiI6MTcyNDA4OTU2NywicGF0aCI6Ii81NjkxNTAxMC8zNTkxOTAwMzgtNjQyOTU4YTItNWRiNS00YzFjLTkwMDgtMWZmNjA5N2U1OTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE3NDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTMxMjJhOWUyNzg5ZGQxZjFhOGM0MDNmYWM1NjkxZDc5ZjJmNjM3NjQ4MTkyMjI5NDRlZjNkNmNjOTFmMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnJdrzQ4sf6be3CWjISdjs8I21RsYccBTjV-sfV8t0U">
> 
> I am closing this issue since its resolved :)

Making a plugin is not much different from making an extention of your own wezterm configuration. I don't see why it wouldn't be a nice addition, especially if you could make it nice and extensible such that other plugins can export "widgets" which could be included in the tabbar.
Feel free to use the plugins I have made as inspiration for how to develop a plugin yourself 😄 these two are quite a bit simpler than resurrect.wezterm if you need inspiration:
[modal.wezterm](https://github.com/MLFlexer/modal.wezterm)
[smart_workspace_switcher.wezterm](https://github.com/MLFlexer/smart_workspace_switcher.wezterm)
