### ISSUE TITLE
Add default workflow to save/load state based on window title

### ISSUE THREAD

**Issue by MLFlexer** [MLFlexer/resurrect.wezterm#47]
Some users might want to load and save state for a window. One way to do this is to load/save based on the window title via. [get_title()](https://wezfurlong.org/wezterm/config/lua/mux-window/get_title.html).

There should at least be a guide in the readme to do this, but probably also expose some default functions for setting it up.
Periodic_save should probably also include a way to save windows based on the title

If this is useful, then it can also be expanded to tab titles and workspacenames

**Comment by MLFlexer** [comment]
@michaelbrusegard with this PR I added the ability to save and restore windows based on the window title. I.e. no need for workspaces which might be something you can use to restore windows without opening new ones.

**Comment by michaelbrusegard** [comment]
@MLFlexer This is brilliant! Would it be possible to also implement it with the workspace switcher plugin? So I can switch windows? That way I can have different windows open at the same time in different «sessions». Also do you have any tips when developing my own plugin in how I can load it locally?

**Comment by MLFlexer** [comment]
> @MLFlexer This is brilliant! Would it be possible to also implement it with the workspace switcher plugin? So I can switch windows? That way I can have different windows open at the same time in different «sessions». 

The workspace plugins "core" is workspaces, so if you change workspaces, then the windows will also change, as that is how Wezterm handles workspaces. I don't think you can have the same window open in multiple workspaces, but you should be able to fake it to some extend by saving your window before changing workspaces, then after you have changed workspace you can load the same workspace. The keybindings in the updated [setup example](https://github.com/MLFlexer/resurrect.wezterm?tab=readme-ov-file#setup-example) can do this.

> Also do you have any tips when developing my own plugin in how I can load it locally?

I would start by making a file in your wezterm config which you can require with `require("<file_name>")` you could also symlink the lua file from your git repository into your config and then require it, like before. 
Note that multifile plugins in wezterm aren't supported very well (as you manually have to extend the lua path) and that the entrypoint to your plugin is `git_root/plugin/init.lua`

**Comment by michaelbrusegard** [comment]
@MLFlexer Can you elaborate on how I can have multiple modules in my plugin, I have already created many lua files and It would b enice if I didnt have to move everything into the init.lua? Is it possible to have a local path inside the wezterm.plugin.require or would I need to use a symlink as you stated with a normal require

**Comment by MLFlexer** [comment]
I dont think you can have local path inside wezterm.plugin.require, but if you clone your repo to `$USER/.local/share/wezterm/plugins` then you might be able to fake it.

To enable mutiple modules you need to change the package.path in your init.lua, like here: https://github.com/MLFlexer/resurrect.wezterm/blob/e172779b4b0ec48bdd6a18967b75c14b3aafd6c5/plugin/init.lua#L31

**Comment by michaelbrusegard** [comment]
> To enable mutiple modules you need to change the package.path in your init.lua, like here:
> 
> https://github.com/MLFlexer/resurrect.wezterm/blob/e172779b4b0ec48bdd6a18967b75c14b3aafd6c5/plugin/init.lua#L31

This approach doesnt work with a symlink when developing locally though

**Comment by MLFlexer** [comment]
> > The workspace plugins "core" is workspaces, so if you change workspaces, then the windows will also change, as that is how Wezterm handles workspaces. I don't think you can have the same window open in multiple workspaces, but you should be able to fake it to some extend by saving your window before changing workspaces, then after you have changed workspace you can load the same workspace. The keybindings in the updated [setup example](https://github.com/MLFlexer/resurrect.wezterm?tab=readme-ov-file#setup-example) can do this.
> 
> I didn't mean having a window open in different workspaces. I was thinking more if it would be possible to have a single workspace, and then have the workspace switcher plugin switch between windows. So I could have two windows open in different "window sessions" and then in each of them I could switch to a different "window session" when I want to. It would be kind of as if windows contained workspaces. This may be limited by the API, maybe it could work with hiding and showing windows, but I am not sure. I think I will live with the limitation of workspaces as I normally only have a single terminal window open at a time.

While it sounds like a great idea, I don't think it is possible with the current API to replace mux windows within a gui. It would be nice to have though

**Comment by MLFlexer** [comment]
> This approach doesn't work with a symlink when developing locally though. I am trying to have a symlink from the plugins folder instead. 

Try and place your plugin in `$USER/.local/share/wezterm/plugins/YOUR_PLUGIN_NAME` and then develop it there, you might have to make it a git repo to make it work. But you should be able to call `wezterm.plugin.require("YOUR_PLUGIN_NAME")` if `YOUR_PLUGIN_NAME` does not contain any special characters

> Would it be beneficial to have a folder with the name of the plugin with all the modules to avoid filing the path with generic names?

Yes that is generally a good idea, there is not a set way of doing this, but avoiding overlap between plugins and/or user configs is always a good idea

**Comment by michaelbrusegard** [comment]
I got it working, by symlinking both the plugin directory and the hidden .git directory :)
