### ISSUE TITLE
Keybind to delete a saved state within the fuzzy picker

### ISSUE THREAD

**Issue by michaelbrusegard** [MLFlexer/resurrect.wezterm#62]
Is it possible to have a keybind (ctrl+x) to delete a saved state when within the fuzzy picker for loading a state instead of having a seperate fuzzy picker when you want to delete. So (ctrl+x) would delete the hovered item? I understand if this is not possible, just wondering

**Comment by MLFlexer** [comment]
I have tried to add keybinds to a fuzzy finder but was unable to do so, see [this issue](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/issues/26)

**Comment by MLFlexer** [comment]
I am not sure I understand your question? Will you wait for Wezterm to allow keybinds in the fuzzy finder? Because I don't think that will happen anytime soon unfortunetly
