### ISSUE TITLE
support for powershell

### ISSUE THREAD

**Issue by mostafa-fm** [MLFlexer/resurrect.wezterm#63]
**Description**
I am using Wezterm on Windows and have configured it to use PowerShell as my shell. When I save a session, the state is not saved correctly. Specifically, the current directory is saved as text within the session file, but it does not restore properly upon loading.

**Expected Behavior**
When I save and load a session, I expect the session to restore to the exact state, including the current working directory within PowerShell.

**Actual Behavior**
The session is saved, but when reloaded, the directory is stored as plain text and does not restore to the correct working directory. The session file contains the following:

`{
  "size": {
    "cols": 158,
    "dpi": 120,
    "pixel_height": 945,
    "pixel_width": 1896,
    "rows": 35
  },
  "tabs": [
    {
      "is_active": true,
      "is_zoomed": false,
      "pane_tree": {
        "alt_screen_active": false,
        "cwd": "C:/Users/user/",
        "domain": "local",
        "height": 35,
        "index": 0,
        "is_active": true,
        "is_zoomed": false,
        "left": 0,
        "pixel_height": 945,
        "pixel_width": 1896,
        "text": "PowerShell 7.4.5\r\nPS C:\\Users\\user> \u001b[93mcd \u001b[37m.\\AppData\\Local\\nvim\\     \u001b[38;5;238m    \r\n\u001b[39mPS C:\\Users\\user\\AppData\\Local\\nvim>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
        "top": 0,
        "width": 158
      },
      "title": ""
    }
  ],
  "title": "session 1"
}`

**Steps to Reproduce**
Configure Wezterm to use PowerShell on Windows.
`config.default_prog = { 'powershell.exe' }`
Open the terminal and change directories.
Save the session.
Load the session.

Environment
Wezterm version: [20240203-110809-5046fc22]

**Comment by joncrangle** [comment]
@mostafa-fm 
Do you have your PowerShell profile integrated with Wezterm according to
[Wezterm windows shell integration] (https://wezfurlong.org/wezterm/shell-integration.html#osc-7-on-windows-with-powershell)?

If so, and it's still not reopening your state, could you please try changing the following in your plugin resurrect directory in `init.lua` and let me know if it works? I don't have access to a Windows PC at the moment to test it.

Change: 
```lua
local process_args = { "pwsh.exe", "-NoProfile", "-Command", cmd }
```

To:
```lua
local process_args = { "powershell.exe", "-NoProfile", "-Command", cmd }
```

**Comment by MLFlexer** [comment]
From the state file I am guessing the should have spawned you in C:/Users/user, but it spawned in some other directory, is that correctly understood?

If so, then it might be a problem with the cwd having / instead of \ chars

If this is not the case, then I would advise u follow @joncrangle advice and check if the shell sets the OSC correctly

**Comment by mostafa-fm** [comment]
@MLFlexer @joncrangle

Thank you! The issue was resolved by configuring the PowerShell profile—I wasn't aware of that.

However, I'm currently facing another issue. I'm not sure if it's related to the WezTerm Resurrect plugin or if it’s a Codeium-related problem. The plugin seems to pick up the Codeium process instead of Neovim. this is in both cmd and PowerShell

Here is the session content:
`{
  "size": {
    "cols": 158,
    "dpi": 120,
    "pixel_height": 945,
    "pixel_width": 1896,
    "rows": 35
  },
  "tabs": [
    {
      "is_active": false,
      "is_zoomed": false,
      "pane_tree": {
        "alt_screen_active": true,
        "cwd": "C:/Users/user",
        "domain": "local",
        "height": 35,
        "index": 0,
        "is_active": true,
        "is_zoomed": false,
        "left": 0,
        "pixel_height": 945,
        "pixel_width": 1896,
        "process": {
          "argv": [
            "C:\\Users\\user/.codeium/bin/1.14.12/language_server_windows_x64.exe",
            "--api_server_url",
            "https://server.codeium.com",
            "--manager_dir",
            "C:\\Users\\user\\AppData\\Local\\Temp\\nvim.0\\8oMy14\\1/codeium/manager"
          ],
          "console": 72,
          "cwd": "C:\\Users\\user\\",
          "executable": "C:\\Users\\user\\.codeium\\bin\\1.14.12\\language_server_windows_x64.exe",
          "name": "language_server_windows_x64.exe",
          "start_time": 133716009499447343,
          "status": "Run"
        },
        "top": 0,
        "width": 158
      },
      "title": ""
    },
    {
      "is_active": true,
      "is_zoomed": false,
      "pane_tree": {
        "alt_screen_active": false,
        "cwd": "C:/mypc",
        "domain": "local",
        "height": 35,
        "index": 0,
        "is_active": true,
        "is_zoomed": false,
        "left": 0,
        "pixel_height": 945,
        "pixel_width": 1896,
        "text": "Windows PowerShell\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nTry the new cross-platform PowerShell \u001b]8;;https://aka.ms/pscore6\u001b\\https://aka.ms/pscore6\r\n\r\n\u001b]8;;\u001b\\PS C:\\Users\\user> \u001b[93mcd\\\r\n\u001b[39mPS C:\\> \u001b[93mcd \u001b[36m'.\\1my pc\\'\r\n\u001b[39mPS C:\\mypc>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
      },
      "title": ""
    }
  ],
  "title": "tessssssssssst"
}
`
I appreciate your work! This is an excellent plugin to use on Windows.
