### ISSUE TITLE
State restore fails due to nil property text on pane_tree

### ISSUE THREAD

**Issue by felixjung** [MLFlexer/resurrect.wezterm#74]
Thanks for this plugin! I've been playing a bit with it in combination with other plugins. Still getting the hang of Wezterm as a tmux replacement though.

When trying to restore a workspace state, I've unfortunately run into what seems to be a bug. Even with a very simple workspace containing a single tab with a split I get this:

```
23:54:11.518 ERROR wezterm_gui::overlay::selector > while processing user-defined-14 event: runtime error: ...xersZsresurrectsDswezterm/plugin/resurrect/tab_state.lua:140: attempt to index a nil value (field 'text')
stack traceback:
        ...xersZsresurrectsDswezterm/plugin/resurrect/tab_state.lua:140: in function 'resurrect.tab_state.default_on_pane_restore'
        ...xersZsresurrectsDswezterm/plugin/resurrect/tab_state.lua:17: in local 'f'
        ...xersZsresurrectsDswezterm/plugin/resurrect/pane_tree.lua:180: in function 'resurrect.pane_tree.fold'
        ...xersZsresurrectsDswezterm/plugin/resurrect/tab_state.lua:96: in function 'resurrect.tab_state.restore_tab'
        ...sZsresurrectsDswezterm/plugin/resurrect/window_state.lua:55: in function 'resurrect.window_state.restore_window'
        ...resurrectsDswezterm/plugin/resurrect/workspace_state.lua:33: in function 'resurrect.workspace_state.restore_workspace'
        /Users/felix/.config/wezterm/plugins/resurrect.lua:41: in upvalue 'callback'
        ...bsDscomsZsMLFlexersZsresurrectsDswezterm/plugin/init.lua:401: in function <...bsDscomsZsMLFlexersZsresurrectsDswezterm/plugin/init.lua:399>
```

I've isolated the issue to the current [tab state code](https://github.com/MLFlexer/resurrect.wezterm/blob/main/plugin/resurrect/tab_state.lua#L135). What should set the text property on the `pane_tree` and why could it be missing?

**Comment by MLFlexer** [comment]
Thanks for creating the issue.

I think the control flow should be an if statement to check if the text is not nill, not just an else branch, so will change that. Hopefully that will fix your issue 😄
